import type { Product, Category, Review } from "./types";

export const categories: Category[] = [
  {
    id: 1,
    name: "mountain",
    nameAr: "دراجات جبلية",
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?q=80&w=2070&auto=format&fit=crop",
    productCount: 8,
  },
  {
    id: 2,
    name: "road",
    nameAr: "دراجات سباق",
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=2070&auto=format&fit=crop",
    productCount: 5,
  },
  {
    id: 3,
    name: "bmx",
    nameAr: "دراجات BMX",
    imageUrl: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?q=80&w=2070&auto=format&fit=crop",
    productCount: 4,
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Trail Blazer Pro",
    nameAr: "ترايل بلايزر برو",
    description: "High-performance mountain bike for trail riding",
    descriptionAr: "دراجة جبلية عالية الأداء مصممة لركوب المسارات الوعرة بكل ثقة وسيطرة. إطارات عريضة وتعليق أمامي متقدم.",
    price: 450,
    originalPrice: 550,
    imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?q=80&w=2022&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?q=80&w=2022&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?q=80&w=2070&auto=format&fit=crop",
    ],
    brand: "Trek",
    categoryId: 1,
    categoryName: "mountain",
    categoryNameAr: "دراجات جبلية",
    featured: true,
    stock: 5,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: 2,
    name: "Speed Demon R5",
    nameAr: "سبيد ديمون R5",
    description: "Lightweight road bike for competitive cycling",
    descriptionAr: "دراجة طريق خفيفة الوزن مثالية للسباقات والجولات الطويلة. هيكل كربون مع نظام تروس احترافي.",
    price: 680,
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=2070&auto=format&fit=crop",
    brand: "Giant",
    categoryId: 2,
    categoryName: "road",
    categoryNameAr: "دراجات سباق",
    featured: true,
    stock: 3,
    rating: 4.9,
    reviewCount: 18,
  },
  {
    id: 3,
    name: "Urban Rider X",
    nameAr: "أوربان رايدر X",
    description: "City commuter bike with comfort geometry",
    descriptionAr: "دراجة مدينة مريحة مثالية للتنقل اليومي. تصميم عملي مع حقيبة خلفية وإضاءة مدمجة.",
    price: 280,
    originalPrice: 320,
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=2070&auto=format&fit=crop",
    brand: "Specialized",
    categoryId: 1,
    categoryName: "mountain",
    categoryNameAr: "دراجات جبلية",
    featured: true,
    stock: 8,
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: 4,
    name: "BMX Street King",
    nameAr: "BMX ستريت كينج",
    description: "Professional BMX for street and park riding",
    descriptionAr: "دراجة BMX احترافية للعروض والحيل. هيكل فولاذي قوي مع عجلات متينة تتحمل الصدمات الشديدة.",
    price: 320,
    imageUrl: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?q=80&w=2070&auto=format&fit=crop",
    brand: "Mongoose",
    categoryId: 3,
    categoryName: "bmx",
    categoryNameAr: "دراجات BMX",
    featured: true,
    stock: 6,
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: 5,
    name: "Mountain King XT",
    nameAr: "ماونتن كينج XT",
    description: "Full suspension mountain bike",
    descriptionAr: "دراجة جبلية بتعليق كامل للمسارات الأكثر تحدياً. نظام تعليق متطور يمتص الصدمات بكفاءة عالية.",
    price: 750,
    originalPrice: 900,
    imageUrl: "https://images.unsplash.com/photo-1576435728678-68d0fbf94946?q=80&w=2068&auto=format&fit=crop",
    brand: "Trek",
    categoryId: 1,
    categoryName: "mountain",
    categoryNameAr: "دراجات جبلية",
    featured: false,
    stock: 2,
    rating: 4.9,
    reviewCount: 9,
  },
  {
    id: 6,
    name: "Enduro Beast",
    nameAr: "إندورو بيست",
    description: "Enduro racing mountain bike",
    descriptionAr: "دراجة إندورو متخصصة للسباقات الجبلية الشديدة. أداء استثنائي في التضاريس الوعرة.",
    price: 520,
    imageUrl: "https://images.unsplash.com/photo-1509116832767-97f6a8694199?q=80&w=1936&auto=format&fit=crop",
    brand: "Cannondale",
    categoryId: 1,
    categoryName: "mountain",
    categoryNameAr: "دراجات جبلية",
    featured: false,
    stock: 4,
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: 7,
    name: "Road Elite Carbon",
    nameAr: "رود إيليت كاربون",
    description: "Carbon fiber road racing bike",
    descriptionAr: "دراجة سباق طريق بهيكل كربون خالص. أخف وزناً وأسرع استجابةً لكل بطل.",
    price: 1200,
    imageUrl: "https://images.unsplash.com/photo-1571333250630-f0230c320b6d?q=80&w=2070&auto=format&fit=crop",
    brand: "Specialized",
    categoryId: 2,
    categoryName: "road",
    categoryNameAr: "دراجات سباق",
    featured: false,
    stock: 2,
    rating: 5.0,
    reviewCount: 7,
  },
  {
    id: 8,
    name: "Kids Rocket",
    nameAr: "كيدز روكيت",
    description: "Kids bike 20 inch for ages 6-10",
    descriptionAr: "دراجة أطفال 20 بوصة مناسبة للأعمار 6-10 سنوات. تصميم ملوّن جذاب مع تروس سهلة الاستخدام.",
    price: 150,
    imageUrl: "https://images.unsplash.com/photo-1591840570929-69a8bca7b14b?q=80&w=1974&auto=format&fit=crop",
    brand: "Trek",
    categoryId: 3,
    categoryName: "bmx",
    categoryNameAr: "دراجات BMX",
    featured: false,
    stock: 10,
    rating: 4.8,
    reviewCount: 22,
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    productId: 1,
    customerName: "أحمد الحسن",
    rating: 5,
    comment: "دراجة ممتازة جداً! جودة عالية وخدمة توصيل سريعة. أنصح الجميع بالشراء من Two Wheels.",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: 2,
    productId: 1,
    customerName: "محمد علي",
    rating: 5,
    comment: "اشتريت هالدراجة من شهر وما عندها أي مشكلة. الأداء ممتاز على المسارات الجبلية.",
    createdAt: "2024-02-20T14:00:00Z",
  },
  {
    id: 3,
    productId: 2,
    customerName: "سارة خالد",
    rating: 5,
    comment: "دراجة السباق أخف ما توقعت وأسرع بكثير من دراجتي القديمة. شكراً Two Wheels!",
    createdAt: "2024-01-10T09:00:00Z",
  },
  {
    id: 4,
    productId: 3,
    customerName: "عمر البكر",
    rating: 4,
    comment: "مناسبة جداً للتنقل في المدينة. مريحة وخفيفة. الوحيد ودّيت لو في ألوان أكثر.",
    createdAt: "2024-03-01T11:00:00Z",
  },
];
